"""daf-jev — a modular, composable client for the TypeSafe Jev (System One)
API.
"""

from daf_jev._errors import (
    APIConnectionError,
    APITimeoutError,
    OverloadedError,
    RateLimitError,
    TypeSafeError,
)
from daf_jev._retry import RetryPolicy
from daf_jev._types import (
    Answer,
    ChoiceAnswer,
    ChoiceQuestion,
    JSONContent,
    NoulAnswer,
    NoulQuestion,
    Question,
    ScoreAnswer,
    ScoreQuestion,
    SystemOneResponse,
    Usage,
    answer_from_wire,
    parse_response,
)
from daf_jev.bayesnet_posteriors import (
    CalibrationPairing,
    PosteriorsSidecar,
    load_posteriors,
    pair_for_calibration,
)
from daf_jev.client import (
    AsyncJevClient,
    JevClient,
    ModelCard,
    open_async_client,
    open_client,
)
from daf_jev.compose import composite_score, confidence_gate, route
from daf_jev.config import (
    Settings,
    load_settings,
    resolve_retry,
    resolve_timeout,
)
from daf_jev.decider import Budget, ConfidenceGate, Decider, DecisionEvent
from daf_jev.decision_backends import (
    AsyncDecisionBackend,
    AsyncHTTPDecisionBackend,
    BackendCapabilities,
    CallReceipt,
    DecisionBackend,
    DecisionPrediction,
    DecisionRequest,
    DecisionResult,
    HTTPDecisionBackend,
    PriorBackend,
    ThreadedAsyncBackend,
)
from daf_jev.evaluate import EvaluationRecord, Evaluator
from daf_jev.graphical import CPT, BayesNet, Edge, Variable, decompose_single_parent
from daf_jev.graphical_elicitation import (
    elicit_cpts,
    elicit_cpts_async,
    propose_structure,
    propose_structure_async,
)
from daf_jev.jaggedness import (
    COIN,
    COIN_NOUL,
    D6,
    JaggednessFixture,
    chi2_sf,
    max_streak,
    noul_choice_delta,
    position_slope,
    run_battery,
    runs_test_z,
    uniform_chi2,
    uniform_deviation,
)
from daf_jev.ledger import UsageLedger, UsageSnapshot
from daf_jev.models import pick_model
from daf_jev.primitives import QuestionSet, choice, noul, score
from daf_jev.providers import (
    ProviderSpec,
    get_provider,
    list_providers,
    register_provider,
)
from daf_jev.reask import ReAskPlan, entropy_bits, next_question, reask_plan
from daf_jev.resilience import CircuitBreaker, CircuitOpenError, CircuitState

__version__ = "0.7.0"

__all__ = [
    "COIN",
    "COIN_NOUL",
    "CPT",
    "D6",
    "APIConnectionError",
    "APITimeoutError",
    "Answer",
    "AsyncDecisionBackend",
    "AsyncHTTPDecisionBackend",
    "AsyncJevClient",
    "BackendCapabilities",
    "BayesNet",
    "Budget",
    "CalibrationPairing",
    "CallReceipt",
    "ChoiceAnswer",
    "ChoiceQuestion",
    "CircuitBreaker",
    "CircuitOpenError",
    "CircuitState",
    "ConfidenceGate",
    "Decider",
    "DecisionBackend",
    "DecisionEvent",
    "DecisionPrediction",
    "DecisionRequest",
    "DecisionResult",
    "Edge",
    "EvaluationRecord",
    "Evaluator",
    "HTTPDecisionBackend",
    "JSONContent",
    "JaggednessFixture",
    "JevClient",
    "ModelCard",
    "NoulAnswer",
    "NoulQuestion",
    "OverloadedError",
    "PosteriorsSidecar",
    "PriorBackend",
    "ProviderSpec",
    "Question",
    "QuestionSet",
    "RateLimitError",
    "ReAskPlan",
    "RetryPolicy",
    "ScoreAnswer",
    "ScoreQuestion",
    "Settings",
    "SystemOneResponse",
    "ThreadedAsyncBackend",
    "TypeSafeError",
    "Usage",
    "UsageLedger",
    "UsageSnapshot",
    "Variable",
    "__version__",
    "answer_from_wire",
    "chi2_sf",
    "choice",
    "composite_score",
    "confidence_gate",
    "decompose_single_parent",
    "elicit_cpts",
    "elicit_cpts_async",
    "entropy_bits",
    "get_provider",
    "list_providers",
    "load_posteriors",
    "load_settings",
    "max_streak",
    "next_question",
    "noul",
    "noul_choice_delta",
    "open_async_client",
    "open_client",
    "pair_for_calibration",
    "parse_response",
    "pick_model",
    "position_slope",
    "propose_structure",
    "propose_structure_async",
    "reask_plan",
    "register_provider",
    "resolve_retry",
    "resolve_timeout",
    "route",
    "run_battery",
    "runs_test_z",
    "score",
    "uniform_chi2",
    "uniform_deviation",
]
